# Generated by Django 5.1.2 on 2024-10-17 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materials', models.ManyToManyField(blank=True, related_name='providers', to='orders.material')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reserved', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.deposit')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.material')),
            ],
        ),
    ]
