app = "dssd-api-grupo14"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "8000"

[build]
dockerfile = "Dockerfile"  # Asegúrate de que este path sea correcto

[[services]]
  internal_port = 8000  # El puerto interno en el que tu aplicación escuchará
  [services.http]
    # Define el comportamiento del servicio HTTP aquí
    enable_http = true
    enable_https = true

  [[services.ports]]
    handlers = ["http"]
    port = 80  # Este es el puerto público que se utilizará para acceder a tu aplicación

processes = ["app"]
    command = "gunicorn deposito.wsgi:application --bind 0.0.0.0:8000"  # Comando para iniciar tu aplicación Django
